### ISSUE TITLE
Home Assistant Error: command GetEnc response channel 0 does not equal requested channel 1

### ISSUE THREAD

**Issue by pszypowicz** [starkillerOG/reolink_aio#13]
**Describe the bug**
There is an error in home assistant: 

```
Logger: reolink_aio.api
Source: components/reolink/host.py:193 
First occurred: 09:52:53 (32 occurrences) 
Last logged: 10:23:55

Host xxx.xxx.xxx.xxx:443: command GetEnc response channel 0 does not equal requested channel 1
```

**To Reproduce**
Go to Home Assistant Logs.

**Expected behavior**
No error.

**Environment:**
Home Assistant 2023.4.1

Reolink Duo Floodlight PoE
sw: v3.0.0.1889_23031702
hw: IPC_529B17B8MP

**Comment by starkillerOG** [comment]
Thanks for reporting this @pszypowicz 
It schould be fixed with this commit: https://github.com/starkillerOG/reolink_aio/commit/db222d3ed2f815b033117a7dc1ef7c7c8851a105

Will get into HomeAssistant in a few days.
