### ISSUE TITLE
RLC-823a PTZ with NVR

### ISSUE THREAD

**Issue by bs42** [starkillerOG/reolink_aio#14]
With HomeAssistant 2023.4.0 I enabled the new integration after deleting the reolink_dev I was using before and added my NVR which found all cameras, however for the RLC-423 the PTZ targets were missing.  I removed the NVR and added the cameras individually and the PTZ targets show up perfectly in the list for the camera, so I don't know if the issue is with the NVR not sending the data over or with the library not handling it the same with the NVR.

NVR is a RLN16-410 with hardware H3MB18, firmware v3.3.0.226_23031645.
RLC-423 has firmware v3.0.0.146_20122309.

I also have an RLC-823a, I don't think the PTZ targets showed up on that one either, but I can't be 100% sure since I don't use that camera the same as the RLC-423.

Anything I can do to help diagnose I'm happy to.

**Comment by starkillerOG** [comment]
@bs42 this issue is most likely already resolved in HA 2023.4.2, could you update and try again?
Please let me know if it is fixed or not.

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by bs42** [comment]
Yes, HA 2023.4.2 fixed the issue.  I see that it knows what types of cameras they are through the NVR which it did not do on the previous version.  Thanks for the update and all the work you are doing on this integration, it is excellent!

**Comment by starkillerOG** [comment]
@bs42 thanks for the feedback, good to hear it is fixed.
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
