### ISSUE TITLE
Trigger quick reply messages manually

### ISSUE THREAD

**Issue by kevdliu** [starkillerOG/reolink_aio#16]
**Describe the bug**
Not really a bug but more of a feature request (unless I totally missed something and the library already supports this, in which case I apologize in advance). I recently got the wifi doorbell and I'm super excited to have found the home assistant integration and this library. I initially misunderstood the auto quick reply capabilities of the integration and thought it meant I could trigger one of the saved quick replies on demand. Now I see it lets you change the auto quick reply settings. With that said is it possible to add support for triggering quick replies manually? It would be a very useful stop gap since the doorbell's ONVIF Profile T capability is not working so well right now. 

Thanks for all your work with this integration and library!

**Environment:**
 - Reolink Doorbell WiFi

**Comment by starkillerOG** [comment]
@kevdliu first of all, thank you very much for sponsering!

I haved discussed this with a Reolink firmware engineer, and currently there is no command in the HTTP API to trigger a quick reply message.
They will (probably) implement this in the future, but it is not available yet, we will have to wait on a new firmware version of the doorbell that makes this possible.
(although I have not checked the latest doorbell firmware).

**Comment by kevdliu** [comment]
Thanks for the quick reply! Finger crossed that Reolink adds it in the future.

**Comment by kevdliu** [comment]
@starkillerOG Might be a question for your contact at Reolink but do you happen to know if the doorbell camera properly supports ONVIF profile T? There seems to be an issue with it returning 401 unauthorized when one attempts to open the RTSP stream with the audio backchannel, whereas it successfully returns the stream without the backchannel. https://github.com/AlexxIT/go2rtc/issues/331#issuecomment-1499046818. Hopefully this is not too off-topic.

**Comment by starkillerOG** [comment]
@kevdliu unfortunately I really would not know, i think it is best to ask support directly.

**Comment by conorlap** [comment]
+1 for this once the firmware allows it! Would be very useful :)

**Comment by starkillerOG** [comment]
@conorlap please also send a message to reolink support and request it be added to the HTTP API, the more people request it, the higher it ends up in their priority list.
They told me they are working on it already, but I did not see any beta firmware or something which has a new HTTP API commond for this.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by conorlap** [comment]
Update from Reolink: 

![Screenshot_20230620_112855_Gmail](https://github.com/starkillerOG/reolink_aio/assets/57415184/4e1b287d-6d21-4199-a9ce-e15213849140)

🥳

**Comment by gary-sargent** [comment]
@starkillerOG have you had any updated from Reolink on this? Is it available in the 2555_23080700 firmware?

**Comment by starkillerOG** [comment]
@gary-sargent nope, I do not have any updates, I am still waiting on a new firmware from Reolink.
As far as I know 2555_23080700 does not include it yet.
You could contact reolink support and ask about it, maybe they have an update...
