### ISSUE TITLE
Streaming playback unusably glitchy

### ISSUE THREAD

**Issue by mattdm** [starkillerOG/reolink_aio#19]
**Describe the bug**

Camera streams play for a couple of seconds, buffer, play for a few more, then buffer, repeatedly.

**To Reproduce**

Pick a camera in the Home Assistant UI. Try to look at a stream.

Same behavior with rtmp, rtsp, and flv.

Happens even with the low-res "sub" screen.

**Expected behavior**

Maybe a little slow to load, then smooth playback.

**Screenshots**

[Screencast from 2023-04-10 11-38-22.webm](https://user-images.githubusercontent.com/123367/230936747-6f3f2e0a-09fc-4bbb-8137-e5a8f43b4fc3.webm)

**Environment:**

Home Assistant: 2023.4.2 (container)

NVR: RLN8-410 (N3MB01), firmware v3.3.0.226_23031609

Cameras:
* Front Stairs, Side Corridor: RLC-510A
* Front Door, Backyard: RLC-842A
* Front Eagle Eye: Duo 2 PoE

Home Assistant is running on a pretty beefy workstation machine, and is connected to the same gigabit ethernet as the NVR. Client system another desktop on the same network.

**Additional context**

Works fine via the NVR web interface.

The "screenshots" mode works fine, although that's kind of horrific.

**Comment by starkillerOG** [comment]
I have not seen this myself in HomeAssistant, it is useally a bit slow to load but then works pretty fine, and I am using the same NVR.
The reolink integration only supplies the stream URLs, the actual streaming is handled by the Home Assistant stream integration.
So I would suggest making a issue in the HomeAssistant core for the stream integration and seeing if they can help.

Did you check if the camera firmware is up to date with https://reolink.com/download-center/?
(update buttons in reolink apps don't work reliably, you will have to upload firmware manually).

I can see the NVR firmware is up to date.

You may also want to give the RTSPtoWebRTC integration a try with the RTSP-To-Web addon: https://github.com/allenporter/stream-addons/tree/main/rtsp-to-web, this can make the streams a lot smoother and faster to load than the build in stream integration.

**Comment by mattdm** [comment]
Hmm, okay. I will have to go to the basement with some firmware files on a USB stick!

And take a look at RTSP-To-Web....
