### ISSUE TITLE
Just a question about integrate Reolink in HA and HACS one 

### ISSUE THREAD

**Issue by Electronlibre2012** [starkillerOG/reolink_aio#25]
**Describe the bug**

Hello @starkillerOG ,

1-i would like to know please why i cant have the video records in media browser with the "official" integration of Reolink in HA?
In your HACS version, i have a folder Reolink where i can found all my videos records on the NVR and can browse it and play videos.

2-the last firmware v3.3.0.226_23031609 for RNL410-8 seems buggy...which one do you advise to use please?

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Reolink NVR/camera model : RNL410-8 / D500 / RLC-520 / Video DOORBELL POE
 - NVR/camera firmware version : v3.3.0.226_23031609

**Additional context**
i cant use the HACS version anymore because all my camera appear "UNKNOWN" in the step of integration when entity are discovered and you can select "rooms"...not nice because i have no issue for month but i make the bad decision of upgrading my NVR to the latest firmware...

**Comment by starkillerOG** [comment]
Hi @Electronlibre2012,
1) playback of old recodings trough the media browser is not yet supported by the build-in reolink integration. That is the only part still missing in the current build-in integration. There is some work beeing done on this by @xannor. The HACS version has a rather complex and dirty implementation, so it needes restructuring, cleanup, simplification and needs to adhere to the HomeAssistant rules.

2) I am using the v3.3.0.226_23031609 on my RLN8-410 N3MB01 withouth any issues. You will need at least this firmware version for proper push messages for the binary sensors (motion, AI people, vehicle, pet, person and doorbell press). I would strongly advise to stick to that firmware untill a newer one is released.

Do you have any issues on the latest firmware with the build-in reolink integration? (besides media browser not beeing available).

**Comment by Electronlibre2012** [comment]
thanks for your reply and all infos.

ok need to wait for record access. 

i have one issue, its the very slow streaming of my cameras feed. localy its usable. when i click on a stream in a picture glance, i have to wait 20 to 30s to have the stream continuesly reading in companion app android. no delay in chrome browser on a pc with lan 2,5gb/s. in companion app or chrome browser, when i am not home, mobile data, grey page for the camera stream and when i click i have to wait 40s or more and the stream is cut, reloading every second or 2 seconds.

i use Cloudflare with ngix reverse proxy, and then go back to duckdns to test. a little better, not really big difference.

if i try with chrome, it almost perfect, almost like i am home on my wifi network. seems the problem is only with companion app.

So not sure its related to the firwmare update or reolink integration, seems the problem is how companion manage h264 streams.

last info, i have a Nvr server, base on Ubuntu 22.04 and the 8 stream are instantanetly displayed in my lovelace page, at home or outside, and i have 2 tapo C310 with exact stream size of my reolink d500 or 520 cameras.

i have try gotortc alittle bit but i have to rest with reolink cameras if there is a big difference. 

Sorry for a lot of info...not really in order, english is not my native language.

**Comment by starkillerOG** [comment]
@Electronlibre2012 The delay in the stream is most likely caused by the stream integration. Please create a seperate issue for that tagging the stream integration stead of the reolink integration.
The reolink integration only provides the correct URL and credentials for the stream, but the actual streaming is handeled by the stream integration.

**Comment by Electronlibre2012** [comment]
@starkillerOG thanks, i agree, i see a few POST about complaining that 4K stream doesnt load in HA and must be downgrade to 2560x1920 to work. I have only cameras with 2560x1920 but even with this resolution, it has so much difficulty to open and play...

I will open a seperate issue.

Thanks for your time and work about thoses Reolink integration!
