### ISSUE TITLE
Support for http/https streams missing [Feature]

### ISSUE THREAD

**Issue by MarkGodwin** [starkillerOG/reolink_aio#3]
**Describe the bug**
The library will return rtmp and rtsp urls, but the Reolink cameras and NVRs also support returning an .flv stream via http. This is the API that Reolink's own web UI uses to view camera feeds, and it is [reported](https://docs.frigate.video/configuration/camera_specific/) to work with less overhead and more reliability than RTSP.

Also, I think RTSP/RTMP don't support a 4k stream from the Reolink cameras, whereas the http(s) streams _might_ (although I don't actually have any 4k cameras to confirm this).

**Expected behavior**
I suggest that when you call `get_stream_source` with `stream` values `http` or `https`, the library could return a URL in this form:
```
http(s)://x.x.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<username>&password=<password>
```

Note the channels are zero-based for the HTTP API. `main`, `ext` and `sub` are all supported.

From the look of the URL, it feels like Reolink might just be forwarding data internally from an RTMP server, so it's possible that this isn't any better than RTMP in practice. However, it does work even with RTMP disabled in the NVR config. It would be interesting to know what the web UI does to download a 4k stream.

**Environment:**
NVR Model: RLN8-410
Build No.: 22120247
Hardware No.: N2MB02
Firmware Version: v3.2.0.214_22120247
Cameras: RLC-410-5MP

**Additional context**
I'm happy to put in a PR if you agree. The next step is to add http/https options to the new official Reolink HA integration.

**Comment by starkillerOG** [comment]
@MarkGodwin I just added the flv stream protocol URL as an option in this library according to the reolink HTTP API guid.
I have not tried it out yet,

I will finished my current work on the binary sensors and then release a new version of this library.
I will then test it out and make a PR for HomeAsssitant to add this as a protocol option.

**Comment by MarkGodwin** [comment]
Great. Let me know if you need any help testing it out.

**Comment by starkillerOG** [comment]
@MarkGodwin @MarosorcH support for the HTTP/HTTPS FLV protocol has been added in this HA PR: https://github.com/home-assistant/core/pull/85576

I have already tested it out on my NVR and the streams seem to work just fine.

Closing this issue, if you have any additional questions, feel free to open it again or create a new issue.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library.
