### ISSUE TITLE
Another way to check firmware instead of using the command CheckFirmware.

### ISSUE THREAD

**Issue by mnpg** [starkillerOG/reolink_aio#30]
Hi @starkillerOG,

i found another way to check the firmware update through the official Reolink Download Center if the cameras do not have the CheckFirmware command.

It's a wordpress server and you can have json results for having these informations .

Here the method : 

 * First step :  Retrieve the GetDevInfo of the camera specially the fields : Model and Hardware No

 * Second step : curl this url below to have all the firmware and product id listed in their database : 
`https://reolink.com/wp-json/reo-v2/download/hardware-version/selection-list`

 * Filter in the return hardware-version json with the GetDevInfo you got (the model and Hardware no). You will have in return a id (#id_hardware_n°#) and an dlProduct>id (#id_model#) for this model and hardware

 * After that third step : curl this url below with these ids you got : 
 `https://reolink.com/wp-json/reo-v2/download/firmware/?dlProductId=#id_model#&hardwareVersion=#id_hardware_n°#&lang=en`

 * In the last json page, you will find the date that the firmware has been release (EPOCH date) : 
 > data > 0 > firmwares > 0 > displayTime
you can compare it with current date and check if the display date is the same the current date

Regards

**Comment by starkillerOG** [comment]
@mnpg that is a greath find!
The build-in firmware check command is really flakey, so I think this method will work a lot better.
This also provides more information such us the new firmware version name and release notes.

I am certainly going to implement this as soon as I have some time!

**Comment by starkillerOG** [comment]
@mnpg I implemented this new method in this PR: https://github.com/starkillerOG/reolink_aio/pull/32 , works greath.
Thank you very much for the suggestion!

**Comment by mnpg** [comment]
@starkillerOG, no problem. I'm pleased to help you and the HA Reolinkers community. Thanks to you 👍 
Just one thing, i add a comment for the PR (ISP settings) that you have merged last week :[#29](https://github.com/starkillerOG/reolink_aio/pull/29#issuecomment-1582363930). Can you take a look because  for these isp settings are linked to getability capabilities and in the code, i ain't see something like that but i'm not sure
Tell me if i'm wrong.
Regards

**Comment by starkillerOG** [comment]
I just added the check of the capabilities in commit: https://github.com/starkillerOG/reolink_aio/commit/21adca678dd4d568e1d8e37ac95b547c3f170bc7
Thanks for making me aware of this.
