### ISSUE TITLE
Unsupported Camera Being Discovered

### ISSUE THREAD

**Issue by zimmra** [starkillerOG/reolink_aio#33]
**Describe the bug**
Reolink Lumus camera is being discovered

**To Reproduce**
Run Home Assistant 2023.6+ with a Reolink Lumus on the same LAN

**Expected behavior**
Prior to 2023.6, the Lumus had never been shown as a recommended/discovered device on my system

**Screenshots**
![image](https://github.com/starkillerOG/reolink_aio/assets/28514085/6f1675d6-cc18-44da-9d55-3c11ecedbbb9)
![image](https://github.com/starkillerOG/reolink_aio/assets/28514085/a0b95c5e-9659-4477-a037-e74f73ba9a94)
![image](https://github.com/starkillerOG/reolink_aio/assets/28514085/de63b9db-098f-4973-b3e8-71614681669e)

**Environment:**
 - Reolink Lumus (IPC_325C7)
 - v2.0.0.705_21052800 (IPC_32516MS15W1P1110000000100)

**Additional context**
Home Assistant discovers the device but is unable to connect.
Easy to ignore, but may cause confusion to users who do not realize it is an unsupported camera.

**Comment by zimmra** [comment]
> You are right, this is a battery powered cam that lacks the HTTP API needed for HomeAssistant.

Not battery powered, but otherwise yeah

**Comment by starkillerOG** [comment]
@zimmra thanks for making me aware this is not a battery camera, I added it to the unsupported list in the documentation.

If you do want to use this camera with HomeAssistant, I suggest you contact Reolink support and ask them if they could add the HTTP API to the firmware of this camera.

**Comment by zimmra** [comment]
> If you do want to use this camera with HomeAssistant, I suggest you contact Reolink support and ask them if they could add the HTTP API to the firmware of this camera.

Have they been receptive to changes like that? Is there a particular channel to communicate with them on?

I've currently got it integrated via Neolink, but would much prefer a native solution.

**Comment by starkillerOG** [comment]
Yes at least they respond fast and do take customer feedback seriously.
I would suggest the reddit channel: https://www.reddit.com/r/reolinkcam/
and/or the customer support: https://support.reolink.com/hc/en-us/requests/new/
