### ISSUE TITLE
FR: Reboot function

### ISSUE THREAD

**Issue by alexdelprete** [starkillerOG/reolink_aio#36]
Hi,

does the Reolink API have a reboot function that could be integrated in HA as a function/service?

I just configured my Reolink Doorbell Wifi, your integration is working fine, but I didn't find a service to reboot it, and have to use the app to do it. Would be good to have this to automate it via HA.

I also wanted to ask about the wifi RSSI level, but I see you just implemented it. Hope to see it soon in HA. :)

Thanks a lot.

**Comment by starkillerOG** [comment]
@alexdelprete I just added the reboot command to this library and it is included in the new release: https://github.com/starkillerOG/reolink_aio/releases/tag/0.7.1

I will add it to HomeAssistant as a button entity in the comming weeks.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by alexdelprete** [comment]
Thanks a lot!! In the future I'll have to order some reolink cameras, will use your affiliate link.

**Comment by alexdelprete** [comment]
Hi @starkillerOG, I see we're at 0.7.3 now, has this been included in HA? Where can I monitor the progress of this in HA? 

Thanks.

**Comment by starkillerOG** [comment]
@alexdelprete Yes I implemented it in HomeAssistant and the PRs got merged, it is already on the dev branch.
The reboot entitie will be available in HomeAssistant 2023.8 which will be released on August 2nd 2023.
So just wait a little bit longer and you can start using it ;)

This was the PR https://github.com/home-assistant/core/pull/96311 where you could have follwed the progress, but it is already merged and done.

**Comment by alexdelprete** [comment]
Sorry, I missed the PR. :)

Thanks for your work.
