### ISSUE TITLE
RLC-810A minimum firmware

### ISSUE THREAD

**Issue by joewesch** [starkillerOG/reolink_aio#39]
Hello, I am using your HA integration with my cameras and everything seems to be working fine, but it complains that the firmware version is not compatible. I see that you have `v3.1.0.956_22041503` listed as the minimum version, but I am running a slightly older version of `v3.0.0.494_21073003` due to the fact that Reolink removed the Interframe Space setting in the latest version. I need this setting to set the camera up properly in my Blue Iris NVR.

Granted, there may be something wrong with my current version that makes it not fully compatible that I am unaware of. Can you tell me if there is a way to see if my current camera version is fully compatible and if it is can we switch the minimum version?

**Comment by starkillerOG** [comment]
@joewesch thank you for the feedback.
I personally do not have a RLC-810A, and set the minimum firmware to the ten latest availble to rule out really old firmwares.

It could very well be that the v3.0.0.494_21073003 firmware works perfectly fine with HomeAssistant.

Could you please thoroughly test all entities available in HomeAssistant for the RLC-810A running firmware v3.0.0.494_21073003 and see if everything works withouth issue?
Could you also look at the list of entities in the documentation here: https://www.home-assistant.io/integrations/reolink/ and see if any entity is missing in HomeAssistant that corresponds to a feature that the RLC-810A should support?

If both points above are confirmed to be working properly on v3.0.0.494_21073003, I will bump down the required firmware version for you.

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by joewesch** [comment]
@starkillerOG yes I am able to see 21 entities on all 6 of my cameras. I am getting Main, Sub, Ext and Snapshot streams along with motion/AI detection, siren, recording and many configuration options. The camera doesn't have PTZ or a light, so those entities are absent as expected. The only entity that shows as not working is the Update entity, but I have my cameras in an isolated VLAN and they do not have access to the internet to update themselves so again that is to be expected as well.

**Comment by joewesch** [comment]
I have created a PR with the proposed changes. Let me know if you have any other questions.

**Comment by starkillerOG** [comment]
@joewesch Thanks for confirming and the PR.
Have merged it and will therefore end up in HomeAssistant in a while.

Will not yet release a new version of reolink-aio since this is a tiny change, but will be bundled with some other changes.
