### ISSUE TITLE
Request: Add Ai Delay Settings into HA

### ISSUE THREAD

**Issue by AstonishingAston** [starkillerOG/reolink_aio#43]
_Sorry if this is not the right place, I can't find anywhere better after the past hour trying to figure out how to contact you._

Request/Suggestion:
I would love to have access to the time delay settings for the Ai person and Ai vehicle detect within HA for each camera individualy.
(Setting in Reolink app are under alarm setting, detection alarm, alarm delay)

I've been using this integration for past few months and absolutely love it, thanks for the work this far!
I like it so much so, I just donated $20 to @starkillerOG as a thank you and also possibly as a part bribe to hopefully looki nto my suggestion/request.. please! 😅

Reason for request/suggestion:
I'm using the ai person/vehicle to trigger lights and notifications (works an absolute treat!) But, when it rains, I've got 2 cameras that get rain on the lense and then causes the Ai triggers to go off randomly thinking the drops are people/cars.

Currently workaround:
When it rains at night, I have to go into Reolink app and change the time delay settings for Ai person/vehicle (normal at 0sec) and change them out to 3 or so seconds while it's raining to avoid faulse triggers on each camera. 

Ideal solution:
If the delay settings were exposed to HA then I could make a simple dashboard button to press when it rains (extending timers) and press when it stops raining (set timers back to 0) or better yet, use local weather to trigger the button automatically!

(2 cameras I do this to are specifically a PoE Duo 2 and PoE RLC-820a)

Hopefully the above all makes sense as to what and why, otherwise I'll be happy to provide more info.

**Comment by starkillerOG** [comment]
@AstonishingAston this is the right place, the HomeAssistant issue tracker is only for issue, but on my libraries you are free to contact me.

Thank you very much for sponsering, much appreciated, and I must admit bribing works ;)

Adding the delay settings seems very reasonable and should be doable.
However, I am going on a vacation starting tommorow evening, so probably do not have time to work on it anymore.
In 2 weeks time I will be back and then I will start coding it, I will keep you informed.

Glad to hear you enjoy the Reolink integration!

**Comment by AstonishingAston** [comment]
Fantastic, stoked to hear!
I'll be eagerly keeping an eye out for some action in the next few weeks. 
In the mean time, hope you have a good vacation 🤙🏻

**Comment by starkillerOG** [comment]
@AstonishingAston Back from vacation and have implemented the feature in these two PRs:
https://github.com/starkillerOG/reolink_aio/commit/b870ba2dbda6faf74ac6e5da2ba043b124ae1abc
https://github.com/home-assistant/core/pull/98398

Will work on some other things today and do some additional testing before releasing a new reolink-aio library version.
Hopefully this will make it into HA 2023.9, will keep you informed.

**Comment by starkillerOG** [comment]
@AstonishingAston the PRs have been merged, and therefore I can confirm that the AI delay entities will indeed be included in HA 2023.9 which will be released on september 6th.

Therefore I will close this issue now, if you have any other problems or feature requests, feel free to open a new issue.

**Comment by AstonishingAston** [comment]
Thank you so much, mate!!
