### ISSUE TITLE
FR: Combined NVR Camera View

### ISSUE THREAD

**Issue by OwnsJo** [starkillerOG/reolink_aio#47]
Sorry if wrong section, couldn't find a reolink specific feature request area.

Requesting combined NVR camera sub view. I have multiple cameras, a NVR Sub camera entity for creating alerts that have combined views in one pic would be great. Trying to minimize additional integrations and would appreciate this feature with native Reolink integration. 

I've signed up for the sponsor. Cheers!

Thanks and keep up the good work.

**Comment by starkillerOG** [comment]
@BGetchell first of all, thank you very much for sponsering, much appriciated!

So in the frontend, it is possible to use the `type: grid` card to combine multiple camera views in one grid.
But I am guessing you want to make a snapshot of a single camera entity and send that in a notification message to your phone, (which makes sense). Unfortunately that is not yet possible I think.

I also checked the Reolink HTTP API, but there currently is not a command to get a single snapshot with multiple cameras.
It does make sense to me however, so I am going to request reolink to add this to the firmware, but unfortunately it may take a long time before and if they add this.

Are there any other features you are missing?

**Comment by OwnsJo** [comment]
Thanks for reviewing my request! No feature missing at the moment. Appreciate it.
