### ISSUE TITLE
Unable to connect to NVR anymore

### ISSUE THREAD

**Issue by Valcob** [starkillerOG/reolink_aio#5]
**Describe the bug**
Each time I try to connect to my NVR I get the same   unable to subscribe issue

**To Reproduce**
Remove the integration. Add it back

**Expected behavior**
We should seamlessly connect to NVR as before

**Screenshots**
![image](https://user-images.githubusercontent.com/37367415/216812533-2c09c810-7e62-4aad-a502-d48dd25e0b49.png)

**Environment:**
Please provide useful information about your environment, like:
RNL8-410

**Comment by starkillerOG** [comment]
@Valcob which firmware is the RLN8-410 running?
You probably have to update the firmware version.
You can download the latest firmware from https://reolink.com/download-center/

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by Valcob** [comment]
checked the version it looks like it's the latest one
![image](https://user-images.githubusercontent.com/37367415/216957070-695404e9-8e6a-4327-92f4-ee99ce7a1c9b.png)
I actually have another HA installation which has the prev version 2023.1 and it work normally there

**Comment by starkillerOG** [comment]
@Valcob you have a very old firmware version from oktober 2021.
The latest firmware for the RLN8-410 N2MB02 is v3.2.0.214_22120247 from december 2022.
Please download that version from https://reolink.com/download-center/ and manually update the NVR by uploading the file.

Then it schould work.
2023.1 did not include the webhook subscriptions to receive push updates for the binary_sensors, it is failing on those subscriptions...

**Comment by Valcob** [comment]
sorry I uploaded the before version it's 3.2.0.214

**Comment by Valcob** [comment]
welp I can say if there any issues some times it's worth to just restart all your crap )))) Now it works :)
Closing the bug.

PS: Update and Restart all you need to do sometimes
