### ISSUE TITLE
How to get access to stream/image from POE duo separately ? 

### ISSUE THREAD

**Issue by fe51** [starkillerOG/reolink_aio#60]
Hi there, 
Thank you very much for your work. 

I'm interested in duo POE models (model 1, 2 or 3), and I'm wondering if it's possible to get the stream from each lens separately, and how? By using channels? 

Thanks in advance

**Comment by starkillerOG** [comment]
@fe51 depending on the DUO model this is implemented diffrently (in the reolink firmware):

**DUO 1**
The Duo 1 will have 2 channels with two seperate camera streams for each lens.
The `stream_channels` property will be [0, 1].
You can get a snapshot image using: `get_snapshot(channel=0, stream="main")` or `get_snapshot(channel=1, stream="main")`
You can get the URL to stream using `get_rtsp_stream_source(channel=0, stream="main")` or `get_rtsp_stream_source(channel=1, stream="main")` or `get_flv_stream_source` or `get_rtmp_stream_source`

**DUO 2 and 3**
The DUO 2 and 3 have a single ultrawide stream/image so the footage of both lenses is combined to a single image/stream inside the firmware of the reolink camera.
The `stream_channels` property will be [0].
You can get the ultra-wide snapshot image using: `get_snapshot(channel=0, stream="main")`
You can get the URL to stream using `get_rtsp_stream_source(channel=0, stream="main")` or `get_flv_stream_source` or `get_rtmp_stream_source`.
Note that this stream will have a weird ultra-wide resolution, so make sure your application can handle that.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by fe51** [comment]
Hi @starkillerOG, thanks a lot for your answer !
