### ISSUE TITLE
Q: Are object tracking & tracked object information supported?

### ISSUE THREAD

**Issue by eecharlie** [starkillerOG/reolink_aio#63]
I think the answer is no after checking the manufacturer API guide and looking through the source a bit (I haven't tried using the library), but I thought I'd ask.  I'm interested in a project where tracked object data would be used to override/implement pan/tilt tracking that keeps the tracked object centered in the overall image and was wondering if the TrackMix would support this.

Or, supposing the object detection & tracking are done separately e.g. in Frigate NVR, are there API commands to make specific (coordinate-based) pan/tilt operations? I saw the up/down left/right but it's unclear whether this moves a fixed amount per command, initiates motion that needs to be stopped, or something else.

What is `GetPtzTraceSection` used for?

Thanks!

**Comment by starkillerOG** [comment]
No there is no position information of detected objects.
You only get True/False for detection of people, pet, vehicle etc. (and push notifications).

GetPtzTraceSection is for the limits of the autoTracking.

zoom can be controlled as a absolute number.
pan/tilt can only be controlled with move operations that will start moving the camera indefinetly untill the stop command is supplied.
Doing a specific step involves sending e.g. "pan left" then a delay of eg. 0.5 seconds then "ptz stop"

Hope this gives you enough info.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
