### ISSUE TITLE
Not an issue. Question

### ISSUE THREAD

**Issue by chrishome7** [starkillerOG/reolink_aio#68]
With the Reolink doorbell "quick reply" messages are exposed and for automations we can select to change these messages. However, we cannot trigger these messages to play (at least that I can see) is there a way to do this?  This would allow people to play recorded messages through the door bell if the person / motion detection triggers or via use of other triggers. Is there even a way to even play those messages via the HA dashboard for those not using the app?

**Comment by starkillerOG** [comment]
@chrishome7 Yes there is, on the latest doorbell firmware the API command needed to PLAY/TRIGGER quick replay audio messages was added and I also already added this to HomeAssistant.

However the API command is not yet included in NVR firmware, so it will only be available when connecting the doorbell directly to HomeAssistant withouth an NVR in-between.
This API command will also be added to the NVR firmware in the future (is already available in the Reolink Home Hub), but you will have to wait a bit for Reolink to release that firmware.

The new select entity is called "Play quick reply message", to directly play the audio
While the old still available entity called "Auto quick reply message" controls which audio is beeing played after a visitor presses the doorbell button (after x seconds).

Please let me know if you have additional questions.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
