### ISSUE TITLE
Home Assistant Logs (ERROR)

### ISSUE THREAD

**Issue by haitham506** [starkillerOG/reolink_aio#69]
**Describe the bug**
Hello, when you have snapshots stream enabled this error keeps showing up (200+ occurrences)
Home Assistant Logs:

```
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:894
integration: Camera (documentation, issues)
First occurred: 6:23:31 PM (12 occurrences)
Last logged: 9:13:04 PM

Error requesting stream: camera.***_snapshots does not support play stream service
Error requesting stream: camera.***_snapshots does not support play stream service
Error requesting stream: camera.***_snapshots does not support play stream service
Error requesting stream: camera.***_snapshots does not support play stream service
```

**To Reproduce**
Enable snapshots stream

**Environment:**
Please provide useful information about your environment, like:
 - Reolink NVR: RLN8-410 (N2MB02)
 - Camera Models: 3x [RLC-510A] + 1x [RLC-811A]
 - NVR/camera firmware version : NVR [v3.4.0.293_24010832] (the error was there even with older firmware)

**Comment by starkillerOG** [comment]
@haitham506 thank you for reporting this issue.
I could reproduce it and I have fixed it in this PR: https://github.com/home-assistant/core/pull/119572
Will likely be resolved in HA 2024.7.0.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
