### ISSUE TITLE
(Feature Request) Need switches to enable/disable email alerts and FTP uploads

### ISSUE THREAD

**Issue by atx32** [starkillerOG/reolink_aio#7]
For automations in Home Assistant, it would be good to have switches that can enable/disable email alerts and FTP uploads. Perhaps this can be added in the future?

**Comment by starkillerOG** [comment]
@atx32 I have already implemented those in this PR https://github.com/home-assistant/core/pull/87943 which is under review now. Hopefully it will be merged before HA 2023.4.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library.

**Comment by starkillerOG** [comment]
Additionally these PRs will add more features:
https://github.com/home-assistant/core/pull/87932
https://github.com/home-assistant/core/pull/87943
https://github.com/home-assistant/core/pull/87946
https://github.com/home-assistant/core/pull/88217
https://github.com/home-assistant/core/pull/88619
https://github.com/home-assistant/core/pull/88687
