### ISSUE TITLE
Reolink Home Hub Connection Issues

### ISSUE THREAD

**Issue by renotp** [starkillerOG/reolink_aio#70]
**Describe the bug**
When trying to add the Home Hub it cannot connect and says "Failed to connect, check the IP address of the camera"

**To Reproduce**
Setup Reolink Home Hub, connect a Reolink battery powered cameras to it (Argus 4 Pro). Head into Home Assistant, it auto discovers the hub, Press configure, enter Home Hub credentials, fails to connect.  In the Home Hub I activated HTTP, HTTPS, RTSP and ONVIF.

**Expected behavior**
Expected to add as my Reolink POE Cameras.

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Reolink Home Hub (latest firmware)
 - Argus 4 Pro latest firmware, activated HTTP, HTTPS, RTSP and ONVIF.

**Comment by starkillerOG** [comment]
Thanks for reporting this issue, I will help you set-up the Home Hub.

Which firmware version are you running?

Could you also enable the RTMP port?

**Comment by renotp** [comment]
Firmware is v3.3.0.313_24052125.

Same outcome with RMTP activated (I have all activated).

regards
________________________________

**Comment by starkillerOG** [comment]
I see the issue:

You need firmware version v3.3.0.330_24061823.
Please download it from the reolink download center: https://m.reolink.com/download-center/
And update it manually.

Please let me know if it works after the update.

**Comment by renotp** [comment]
So this version is not picked up by the automatic firmware upgrader ?

I'll upgrade and retry.

Thanks
________________________________

**Comment by starkillerOG** [comment]
No it is not pick-up up by the automatic update.

**Comment by renotp** [comment]
Works perfectly, thank you for your assistance.


________________________________

**Comment by renotp** [comment]
Yep, all features seem to work perfectly.

Thanks for your help.

Regards
Paul
________________________________
