### ISSUE TITLE
REolink setup failed

### ISSUE THREAD

**Issue by tgrinnall** [starkillerOG/reolink_aio#74]
**Describe the bug**
HA suggested for me to update the FW on my Reolink system. I updated the FW and after that i get a setup  error on HA's reolink integration. the error says failed setup, will retry: Error while trying to setup (then my ip): client connector error during login of host (ip): Host (ip) : connection error: Cannot connect to host (ip) ssl:dafault(connect call failed(ip). i had it working on the old FW. but as soon as i updated it i got that error. I also use a ! in my password.

**To Reproduce**
I restarted the Reolink and also HA and still get the error

**Environment:**
Please provide useful information about your environment, like:
 - Hardware H3MB18 model RLN16-10
 - NVR/camera firmware version V3.4.0.293_24010833

**Additional context**
HA FW CORE 2024.8.1 
SUPERVISOR 2024.08.0
OP SYSTEM 13.0
FRONTEND 20240809.0

**Comment by starkillerOG** [comment]
Most likely the ports have been closed due to the firmware update.
Use the reolink mobile app or PC cliënt to open the HTTPS port and RTMP port.

**Comment by tgrinnall** [comment]
Ok! That fixed it thanks.

**Comment by starkillerOG** [comment]
Glad it is working again for you!

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
