### ISSUE TITLE
Connecting to the E1 Pro via rtsp

### ISSUE THREAD

**Issue by omergranoviter-holosis** [starkillerOG/reolink_aio#75]
Hi, I am unable to connect to the host for my E1 Pro camera. 
host = api.Host(host='xxx', username='xxx', password='xxx', port=xxx, protocol='rtsp', stream='main')

Am I using it correctly? Can't find any relevant documentation.

**Comment by starkillerOG** [comment]
The E1 Pro does not have a web interface and can therefore not work with this library.

I don't have proper documentation for this library yet, writing proper docs here is still on my to do list.

For a list of tested models see: https://www.home-assistant.io/integrations/reolink/#tested-models
