### ISSUE TITLE
Suggestion for playback

### ISSUE THREAD

**Issue by apocaliss92** [starkillerOG/reolink_aio#84]
Hey, very nice repository this! This is basically a living documentation for me, trying to integrate reolink cameras on 3th party systems
Everything works very well but I'm struggling with one point, I am trying to stream the videoclips from an homehub and I could not find any way to playback them, only download locally. Do you have any suggestion for me to sort this thing out? 

On the reolink app I don't think they download all the clips, or maybe yes? They are very snappy to be shown. Could it be it fetches only a few frames while the clips is downloaded in background? 

Thanks a lot and compliments for the huge work here!

**Comment by apocaliss92** [comment]
Nevermind, seems like Playback should be working :)

**Comment by starkillerOG** [comment]
Glad you were able to figure it out.
Normally you can just use the MP4 as live playback.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
