### ISSUE TITLE
Minor issue with output in example code

### ISSUE THREAD

**Issue by ncul777** [starkillerOG/reolink_aio#86]
This ia a minor issue when using the example code from the readme to connect to a camera / home hub. 

The print line outputs the following when connecting to a Homehub
`It is an NVR: %s, number of channels: %s, True, 8`

Suggest to change to
`print(f"It is an NVR: {host.is_nvr}, number of channels: {host.num_channels}")` 

so that output will be as expected:
`It is an NVR: True, number of channels: 8`

Environment: Python 3.11.2 running on Raspberry Pi 4B

**Comment by starkillerOG** [comment]
Thanks for pointing this out.
I have corrected the example.

I should really spend some time on the docs.....

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) this library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
