### ISSUE TITLE
Question about motion events

### ISSUE THREAD

**Issue by auanasgheps** [starkillerOG/reolink_aio#88]
Hi there,
Thanks for the great job you're doing to support Reolink devices in Home Assistant!

I've got a question for you since you're an expert in this topic. 

I'm facing a very dumb and questionable aspect of my E1 Zoom camera and I'm wondering if we could address it somehow.

This camera, and potentially others, have a very, very dumb "Motion detection". I am not talking about AI (lol) Human and Animal tracking, I'm talking about the basic, standard motion detection.

Well, it's a bit too standard, because it's triggered by camera events, such as turning ON/OFF the night vision or moving the camera using the app. Do you think there's a way to get a motion detection withoth these camera initiated events?

This is what I did have with my crappy and hacked Yi Camera [with this firmware](https://github.com/roleoroleo/yi-hack-Allwinner-v2): the standard motion detection was smart enought to not trigger when actions were performed by the camera.

Also, for the record, I opened a case with Reolink and pushed for an improvement, but they provided a generic response and obviously they'll never do it.

**Comment by starkillerOG** [comment]
@auanasgheps unfortunately that will be very hard for me to solve.
The motion detection just analyses the picture, if the picture changes more than a thershold it will trigger the motion event.
Of course Reolink should be able to supress motion events for a few seconds the moment they change a camera setting like day/night mode/floodlight/turn the camera. But that is not implemented in the firmware.

Not much else you can do than what you did, open a support ticket with Reolink....

Sorry I could not help you.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
