### ISSUE TITLE
Home Assistant integration doesn't list package detection as binary sensor

### ISSUE THREAD

**Issue by chippoman** [starkillerOG/reolink_aio#89]
Sorry, not sure if I should report this issue here or in the HA github. Figured I'd post here fist.

I have a Reolink Video Doorbell White Wifi which has package detection. I've confirmed that reolink_aio sees this:

```
from reolink_aio.api import Host
import asyncio

async def print_capabilities():
    host = Host('192.168.0.101','admin', 'xxxxx', port=80)
    await host.get_host_data()
    print(host.ai_supported_types(0))
    await host.logout()

if __name__ == "__main__":
    asyncio.run(print_capabilities())
```

This returns:

```
['package', 'people']
```

But when I open the Reolink device page in HA, I don't see any binary sensors or entities that refer to package. I do see person though.

The debug log from HA [debug.txt](https://github.com/user-attachments/files/17782262/debug.txt) shows that it's seeing package for ai_type.

2024-11-15 17:51:42.208 DEBUG (MainThread) [reolink_aio.api] Front door/192.168.0.101:443::send() HTTP Request body =
[{'cmd': 'GetEnc', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetIsp', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetEvents', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetIrLights', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetPowerLed', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetAudioCfg', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetAutoReply', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetImage', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetEmailV20', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetPushV20', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetFtpV20', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetRecV20', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetAudioAlarmV20', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetMdAlarm', 'action': 0, 'param': {'channel': 0}}, {'cmd': 'GetAiAlarm', 'action': 0, **_'param': {'channel': 0, 'ai_type': 'package'}}_**, {'cmd': 'GetAiAlarm', 'action': 0, 'param': {'channel': 0, 'ai_type': 'people'}}, {'cmd': 'GetWifiSignal', 'action': 0, 'param': {}}]

So I'm not sure why the HA device page and entities don't have any sensors for package.

**Comment by chippoman** [comment]
I'm an idiot.

My Home Assistant Core was way out of date (2023.12). I updated to 2024.11 and I can see the package binary sensor now.

**Comment by starkillerOG** [comment]
Yea that was a really old HA version.
Glad you figured it out.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
