### ISSUE TITLE
Doorbell Chime Silent Mode

### ISSUE THREAD

**Issue by lwis** [starkillerOG/reolink_aio#90]
v3.0.0.4110 of the Reolink Doorbell contained the change "Integrate Reolink Chime silent mode", this doesn't seem to be exposed through their app, but I was wondering if this functionality could be supported by this library? Thanks!

**Comment by starkillerOG** [comment]
I also saw that one in the release notes.
However if its not available in the Reolink app/client/web client, there is no way to figure out the commands I need to send.
Moreover it will most likely be very buggy if its not yet implemented in the Reolink app/client
So unfortunately we will have to wait for Reolink to properly support it first.
