### ISSUE TITLE
update_firmware reports no new firmware available but _check_reolink_firmware reports there is. 

### ISSUE THREAD

**Issue by redfrogprog** [starkillerOG/reolink_aio#96]
**Describe the bug**
Running `_check_reolink_firmware` for channel 3 which is a RLC-811A | IPC_523128M8MP | v3.1.0.989_22051908 reports new software version of v3.1.0.1643_2402219117 available. However running `await host.update_firmware(3)` reports 
```
Exception has occurred: InvalidParameterError
upload_firmware: no new firmware available for Driveway 2, please first check using check_new_firmware **function**
```

**To Reproduce**
```py
async def print_channels():
    # initialize the host
    host = Host('192.x.x.x','username', '******', port=443)
    # connect and obtain/cache device settings and capabilities
    await host.get_host_data()
    print(f"It is an NVR: {host.is_nvr}, number of channels: {len(host.channels)}")
    print(f"{host.model} | {host.hardware_version} | {host.sw_version}\n")
    print(f"MAC: {host.mac_address}")
    print("\n\n")
    
    for c in host.channels:
        print(f"{c} | {host.camera_name(c)} | {host.camera_model(c)} | {host.camera_hardware_version(c)} | {host.camera_sw_version(c)}\n")
        print(await host._check_reolink_firmware(c))
        
    # Test updating firmware, 
    await host.update_firmware(3)
    
    # Test check firmware, exception KeyError
    #await host.check_new_firmware(host.channels)  

    
    # close the device connection
    await host.logout()    
 ```

**Expected behavior**
When calling `await host.update_firmware(channel)` and a new version is available it should upload and update. 

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - RLN8-410 | N7MB01 | v3.5.1.356_24110154
 - RLC-811A | IPC_523128M8MP | v3.1.0.989_22051908
 - Python 3.11.9
 - VSCode
 - API version 0.11.5
 - camera is directly connected to NVR

**Additional context**
I am running this with python 3.11.9 via vscode. I have successfully used this library to alter the led setting per camera before (Halloween time to turn led's off at dusk and on after we turn off the display). Recently replaced my RLN8-410 due to HDD failure warranty issue with same RLN8-410 and HW version and thought about updating camera firmware. 

I am NOT using Home Assistant since SWMBO has not funded that project yet :) 

Not sure if its related however `await host.check_new_firmware(host.channels)` returns  
```
Exception has occurred: KeyError
None
```

**Comment by starkillerOG** [comment]
This is because you are running "_check_reolink_firmware" which is a internall function which you should not call.
You should be calling "check_new_firmware" instead.

So adjust your script to:
```
async def print_channels():
    # initialize the host
    host = Host('192.x.x.x','username', '******', port=443)
    # connect and obtain/cache device settings and capabilities
    await host.get_host_data()
    print(f"It is an NVR: {host.is_nvr}, number of channels: {len(host.channels)}")
    print(f"{host.model} | {host.hardware_version} | {host.sw_version}\n")
    print(f"MAC: {host.mac_address}")
    print("\n\n")
    
    await host.check_new_firmware()

    for c in host.channels:
        print(f"{c} | {host.camera_name(c)} | {host.camera_model(c)} | {host.camera_hardware_version(c)} | {host.camera_sw_version(c)} | {host.firmware_update_available(c)}\n")
        
    # Test updating firmware, 
    await host.update_firmware(3)
        
    # close the device connection
    await host.logout()  
```

**Comment by starkillerOG** [comment]
I did indeed replicate the "KeyError" in the `await host.check_new_firmware(host.channels)`.
This occurs if "None" (the host itself) is not present in the list to check.

Thanks for reporting this bug.

I have resolved it in this commit: https://github.com/starkillerOG/reolink_aio/commit/75fda9d2b31fb5e63845a51b1af45a4ae8277bd1

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by redfrogprog** [comment]
@starkillerOG 

executing `await host.check_new_firmware(host.channels)` doesn't not work quite as I think it should. 

when calling, it just returns False when provided the entire list of channels on the NVR. However, this is not valid. Two cameras are current in my NVR, three are not current. if I am asking for a check on the entire list of cameras, then it I'd expect it to check each one and return a mixed result list. 

firmware_update_available(channel) does return solid values now. 

Command: 
```py
    for c in host.channels:
        print(f"{c} | {host.camera_name(c)} | {host.camera_model(c)} | {host.camera_hardware_version(c)} | {host.camera_sw_version(c)} | Firmware Update Avail: {host.firmware_update_available(c)}")
        print(f"Lastest Firmware: {await host._check_reolink_firmware(c)}\n")
```

Result:
```
0 | Driveway 1 | RLC-811A | IPC_523128M8MP | v3.1.0.1643_2402219117 | Firmware Update Avail: False
Lastest Firmware: <SoftwareVersion: v3.1.0.1643_2402219117>

1 | Doorbell | Reolink Video Doorbell PoE-W | DB_566128M5MP_P_W | v3.0.0.4110_2410111128 | Firmware Update Avail: False
Lastest Firmware: <SoftwareVersion: v3.0.0.41102410111128>

2 | Yard 2 | RLC-811A | IPC_523128M8MP | v3.1.0.989_22051908 | Firmware Update Avail: <SoftwareVersion: v3.1.0.1643_2402219117>
Lastest Firmware: <SoftwareVersion: v3.1.0.1643_2402219117>

3 | Driveway 2 | RLC-811A | IPC_523128M8MP | v3.1.0.989_22051908 | Firmware Update Avail: <SoftwareVersion: v3.1.0.1643_2402219117>
Lastest Firmware: <SoftwareVersion: v3.1.0.1643_2402219117>

4 | Yard 1 | RLC-811A | IPC_523128M8MP | v3.1.0.989_22051908 | Firmware Update Avail: <SoftwareVersion: v3.1.0.1643_2402219117>
Lastest Firmware: <SoftwareVersion: v3.1.0.1643_2402219117>
```

I do understand using a method call with `_` is not advisable, however, for this case, its really good for troubleshooting and digging into to the fun! Normally I don't use others _ or __ since its implementation or existence is not promised.

**Comment by redfrogprog** [comment]
Looks like it just returns whether or not the HOST (in my case an NVR) needs an update vice returning the camera statuses. My chain of thought is that if I pass in the channel list, I am asking it to test camera firmware versions (which it does) however the return result is misleading in my use case. 


`return latest_sw_version_host`

**Comment by starkillerOG** [comment]
I checked and HA is not using the return anymore.
Therefore I now changed the return type to a dictionary, hopefully that makes more sence: https://github.com/starkillerOG/reolink_aio/commit/4fc4aebf12cda5a66fa6bcc8c63d87d745b4fb70

**Comment by redfrogprog** [comment]
That should handle it gracefully. Then the user can poll the dictionary to check and see. You are a victim of your own success! Dealing code creep :) nice library and very well done sir.
